### ISSUE TITLE
Code that uses include/cg/primitives/range.h not building sometimes

### ISSUE THREAD

**Issue by dvbobrov** [mcquay239/cg#2]
Error messages:
.../cg/include/cg/primitives/range.h:43:22: error: ‘max’ is not a member of ‘std’
.../cg/include/cg/primitives/range.h:43:46: error: ‘min’ is not a member of ‘std’

Fix: add "#include <algorithm>" to range.h

**Comment by mcquay239** [comment]
Thanks, Dmitry.
