### ISSUE TITLE
Visualizer bug

### ISSUE THREAD

**Issue by dvbobrov** [mcquay239/cg#25]
In rectangle_intersects_segment: move the bottom right corner to the left and higher than top left one. Then move the segment into the rectangle. Visualizer will show they do not intersect. Quick fix for rectangle_intersects_segment.cpp:

```
 bool on_release(const point_2f & p)
 {
      rbutton_pressed_ = false;
+     r_.x = {std::min(r_.x.inf, r_.x.sup), std::max(r_.x.inf, r_.x.sup)};
+     r_.y = {std::min(r_.y.inf, r_.y.sup), std::max(r_.y.inf, r_.y.sup)};
      return false;
 }
```

**Comment by mcquay239** [comment]
пофиксил так, чтобы не было противоречий в процессе изменения прямоугольника
