### ISSUE TITLE
epsilon in orientation_d

### ISSUE THREAD

**Issue by bminaiev** [mcquay239/cg#4]
In file "cg / include / cg / operations / orientation.h":
Based on your article (http://habrahabr.ru/post/138168/), epsilon should be equal to "(fabs(l) + fabs(r)) \* 4 \* std::numeric_limits<double>::epsilon();" instead of "(fabs(l) + fabs(r)) \* 8 \* std::numeric_limits<double>::epsilon();" (becouse real epsilon is two times smaller than stl's).

**Comment by mcquay239** [comment]
That's right if rounding flag is set to closest. But flag can be set to
infinity.

But there is a way to reduce this multiplier and if you do it (and prove)
I'll apply your pull request.
