### ISSUE TITLE
CTest

### ISSUE THREAD

**Issue by ZumZoom** [mcquay239/cg#6]
Почему бы не прикрутить ctest к проекту, ведь это совершенно бесплатно делается в нашем случае. Получим замечательную систему запуска всех или выборочных тестов прямо из папки build.

**Comment by ZumZoom** [comment]
Тем временем, я понял, как красиво запускать тесты и без CTest, но все равно можем пообсуждать этот вопрос :)

**Comment by dvbobrov** [comment]
Чем он лучше GTest?

**Comment by ZumZoom** [comment]
Это не замена GTest, а просто инструмент для запуска тестов. Посмотри мой comp_geom репозиторий, я его там поюзал. Основная плюшка в том, что структуру папки с тестами можно сделать аналогичной структуре всего проекта без сильных телодвижений в CMakeLists.txt. Имхо, когда файлов с тестами станет больше двадцати, вопрос как в них ориентироваться будет актуален :) А еще он пишет вывод в лог, что также может быть удобно для большого количества тестов :)

**Comment by mcquay239** [comment]
А стоит ли это делать? Какие бонусы?
